### ISSUE TITLE
Error in automated_testing/evaluator/test_code.py

### ISSUE THREAD

**Issue by HYZ17** [WeixiangYAN/CodeScope#1]
when I tried to run `python evaluator/save_codes.py` and then `python evaluator/test_codes.py`, I encountered the error: `FileNotFoundError: [Errno 2] No such file or directory: 'codes/c/4591'`.  

Then I discovered that there may be an error in the ID in the jsonl file , but after fixing this error, I encountered the following error `Error occurred while executing command: [Errno 2] No such file or directory: 'gcc -fprofile-arcs -ftest-coverage -fPIC -O0 code.c -o code'
CompletedProcess(args='gcc -fprofile-arcs -ftest-coverage -fPIC -O0 code.c -o code', returncode=-1, stdout='', stderr="[Errno 2] No such file or directory: 'gcc -fprofile-arcs -ftest-coverage -fPIC -O0 code.c -o code'")`

**Comment by HaitianLiu22** [comment]
@HYZ17  Thank you for raising this issue. The data we released changed the "id", so there is an inconsistency with the "id" saved during inference. I followed the steps below to execute without problems. It took about 12min:
1. `cd automated_testing`
2. replace `data/automated_testing_data.jsonl` with [inference version](https://drive.google.com/file/d/1TINGMSpbKSM50Sbv2K_aQAwtRPU9Pcbp/view?usp=sharing)
3. `cd evaluator`
4. `python save_codes.py`
5. `python test_codes.py --result_name automated_testing_result_gpt4.jsonl`
